### ISSUE TITLE
Functional MCDU, more details like the a320 family

### ISSUE THREAD

**Issue by lam3344** [JMaverick16/Airbus_A330#85]
Your a330 is a good plane in the Flightgear. So, as a way to attract more people, you could do like the a320, more realistics details, functional MCDU, doors, new sounds and new modeling.

**Comment by SP-NTX** [comment]
![image](https://github.com/JMaverick16/Airbus_A330/assets/72032903/00450bff-f449-4bbc-a2f2-0310dc2b410c)
... and this issue is exactly as senseless as the one on a320 and other ones I had to comment today.... Okay but you know all those things a) will take a lot of time b) are hard to do. Feel free to do them yourself.

**Comment by Octal450** [comment]
Not something that should be in an issue. Develop is on hold for now also.
