### ISSUE TITLE
3 features for the A330-200 (Request)

### ISSUE THREAD

**Issue by Bongoduk** [JMaverick16/Airbus_A330#87]
Hi, I've been a Flightgear pilot for a while now and have been wondering if someone could update the a330-200. Issue #1, a330 cockpit. it isn't that the cockpit is bad its just missing some key components that makes the a330 the a330, like a 3rd MCDU. Issue #2, this is more of a request than an issue but can the Hawaiian airlines livery for the a330-200 be updated to the newer livery? Issue #3, theres an issue with the flaps... i know you know the flaps system is outdated on the a330. it would be nice for it to be fixed. The a330 is my fav so can you plz fix? Thanks!

**Comment by Octal450** [comment]
This isn't appropriate for an issues thread.
What is the issue with the flaps?

Currently the system is not planned to be updated anytime soon besides bugfixes.

Kind Regards,
Josh

**Comment by Bongoduk** [comment]
Apologies and I totally understand if you can’t update the aircraft anytime
soon. Take care!

**Comment by Octal450** [comment]
Hi,
Well the plane has not been in active development since 2019 due to that we shifted focus to the A320. In the future I'd like to come back and finish the A330 but it's not something that will happen anytime soon.

If you can tell me what the bug with the flaps is, I might be able to fix it. It just *probably* won't be rewritten to the new axis system anytime soon.

Kind Regards,
Josh
